### ISSUE TITLE
Segentation Fault

### ISSUE THREAD

**Issue by DenofTranquility** [ThatcherC/Terrain2STL#28]
I have come across an issue with a segmentation fault. I changed the location of the filenames and it appears to cause the fault...
When using a path as the output destination I get the fault.
- `./stls/test.stl`
- `stls/test.stl` 

Both of these failed.

**Comment by ThatcherC** [comment]
Do you have an `stls/` directory in your local Terrain2STL folder? I think what's going on here is that the program is trying to open a file in a directory that doesn't exist. I just pushed an update to master that should provide a warning rather than segfaulting in this case - try that out if you can and see if the segfault goes away.

The other thing to do would be to make an `stls/` directory in your `Terrain2STL/` directory. With that in place I think everything will work. Let me know how it goes!

**Comment by DenofTranquility** [comment]
I didn't have an `stls/` directory in the Terrain2STL folder although when I had specified that as a path elsewhere there was one in that location. I have downloaded the updated versions of the files today and have tried different paths, pretty much the same ones as above and haven't had any issues.

**Comment by ThatcherC** [comment]
Awesome! Glad to hear it's working better now.
