### ISSUE TITLE
Different proportion between selection and stl

### ISSUE THREAD

**Issue by xuv** [ThatcherC/Terrain2STL#6]
Hello.

This is a great program. Thanks for putting it up. Really love it.
I do have a question (that sounds like a newbie question), but I see a difference between the proportion of the area selected in the map and the resulting stl. See screenshots here under.

![terrain](https://cloud.githubusercontent.com/assets/192539/6754511/71828a38-cef3-11e4-96fc-1ed6e4289179.png)
![stl](https://cloud.githubusercontent.com/assets/192539/6754514/7521d810-cef3-11e4-8238-03c4992bf8b4.png)

I'm wondering if the stl has to be scaled or not. And where does this difference comes from?
Thanks.

**Comment by ThatcherC** [comment]
This is a question that has come up more than once in the past, and I'm not sure of the answer. I can tell you where the distortion you noticed comes from, though. The short version is, the distortion is an artifact of how the map is set up, and I'm not sure whether making the model square or rectangular (to match what you see on screen) is more accurate. Here's the long version:

The Google Maps API uses what's called a [Mercator Projection](http://en.wikipedia.org/wiki/Mercator_projection). It's the type of map that you most commonly used in flat, 2D images, like paper or computer maps. However, it doesn't represent the Earth as it really is - it stretches the poles of Earth horizontally, making places like Antartica, Russia, and Canada look much bigger than they are.

Because of the use of the Mercator project, the shape of the selection box changes shape on screen as you move north or south. The dimensions of the box in degrees is the same anywhere in the world. A given box, say of 1°x1°, is 1°x1° anywhere you put it. However, as you move further north or south, the planet tapers because it is a sphere. Therefore, the top of the selection box will be short than the bottom, if measured in a miles or kilometers. Google Maps compensates for this distortion by showing the box to stretch into a taller and taller rectangle as you move toward the poles.

I think what I might do is make an option on the site to have the model be square or what you actually see on screen. I'm not sure which is better: the square is easier to physically work with and pretty accurate for most of the world, but the rectangular shape would match what you see on screen.

**Comment by xuv** [comment]
Thank you for this long answer. I had the intuition of this. But I'm glad to have the technical answer. And I would favor what you have now as a solution. Keep it as close to reality as it can. Distortion of the map is one thing. Distortion of the 3D model makes less sense.

I'm sorry if this was already explained in the documentation. I didn't read it. Maybe to avoid further questioning, you'd like to add this explanation in the doc. 

Again, thanks for this and for the great app. Looking forward to any improvement you will make.

**Comment by ThatcherC** [comment]
The site now produces models that match the map.
